# Generated by Django 3.0.8 on 2020-08-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='book_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='book_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Book'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='client_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Client', verbose_name='Client'),
            preserve_default=False,
        ),
    ]
