# Generated by Django 3.0.8 on 2020-08-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200806_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=10, verbose_name='CPF'),
        ),
    ]
